"""empty message

Revision ID: 92d226a10c99
Revises: 84f681382e7a
Create Date: 2024-01-28 19:04:56.123508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d226a10c99'
down_revision = '84f681382e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('amount_of_traveler', sa.Integer(), nullable=True),
    sa.Column('grand_total', sa.BIGINT(), nullable=True),
    sa.Column('insurance', sa.Boolean(), nullable=True),
    sa.Column('price', sa.BIGINT(), nullable=True),
    sa.Column('refundable', sa.Boolean(), nullable=True),
    sa.Column('selected_seats', sa.String(length=64), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
